### ISSUE TITLE
Adding a Logo

### ISSUE THREAD

**Issue by Shubbu-07** [itsankitbhusal/portfolio#2]
Logo is not there in navbar. Logo should be added.

**Comment by Shubbu-07** [comment]
Please assign me this issue.

**Comment by itsankitbhusal** [comment]
@Shubbu-07 you can start working on this issue now 👍

**Comment by Shubbu-07** [comment]
Can you add Hacktoberfest label on this issue.

**Comment by itsankitbhusal** [comment]
@Shubbu-07 already added and hacktoberfest-accepted label will be added after the pull request made 👍

**Comment by Shubbu-07** [comment]
Ok, I'll start working on it.

**Comment by Shubbu-07** [comment]
Hello @itsankitbhusal, I've fixed issue #1. Please check it out

**Comment by Shubbu-07** [comment]
Hello, @itsankitbhusal I've committed changes in a single PR. Please check it out. If any mistakes, then inform me. Overall both the issues are fixed.

**Comment by itsankitbhusal** [comment]
@Shubbu-07  Make sure you only create a single PR for one issue from now onwards. Only PR are merged not the issues.

**Comment by MeetD99** [comment]
Is this Issue still open for work, I would like to contribute.

**Comment by itsankitbhusal** [comment]
> Is this Issue still open for work, I would like to contribute.

already assigned to @Shubbu-07
