### ISSUE TITLE
Change Github icon in footer & Move Download button to centre

### ISSUE THREAD

**Issue by Shubbu-07** [itsankitbhusal/portfolio#4]
![Screenshot 2023-10-16 235929](https://github.com/itsankitbhusal/portfolio/assets/95517382/9bdbef92-bfee-4d36-8c61-0ecc2b4c9c15)
Github icon should be changed to the latest one.

![Screenshot 2023-10-17 000046](https://github.com/itsankitbhusal/portfolio/assets/95517382/a93d9059-0adb-4d09-a606-2e1c0dc551c1)
Download button should be moved to centre.

**Comment by itsankitbhusal** [comment]
I didn't think this is necessary for now, you can improve the whole page design if necessary.

**Comment by Shubbu-07** [comment]
Ok, I'll see for any more issues that are to be fixed.
